spring:
  application:
    name: api-gateway
  cloud:
    config:
      label: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    hostname: api-gateway

jwt:
  secret-key: "6bc18dff62463c49343d083ae0e523fbfb88d4d45b4a9cb62e86d0c53bd9b870"
  authorities-key: "roles"

route:
  auth: "lb://auth-service"
  user: "lb://user-management-service"
  rest: "lb://rest-data-provider"

redis:
  host: "redis"
  port: "6380"

circuit-breaker-name: "circuit-breaker"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
