spring:
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret-key: "6bc18dff62463c49343d083ae0e523fbfb88d4d45b4a9cb62e86d0c53bd9b870"
  authorities-key: "roles"

route:
  auth: "lb://auth-service"
  user: "lb://user-management-service"
  rest: "lb://rest-data-provider"

redis:
  host: "localhost"
  port: "6379"

circuit-breaker-name: "circuit-breaker"