spring:
  application:
    name: auth-service
  cloud:
    config:
      label: docker
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    hostname: auth-service

jwt:
  secret-key: "6bc18dff62463c49343d083ae0e523fbfb88d4d45b4a9cb62e86d0c53bd9b870"
  authorities-key: "roles"
  access-token-expiration: 3600000 # an hour
  refresh-token-expiration: 86400000 # a day

redis:
  host: "redis"
  port: "6380"

rabbitmq:
  exchange: user-exchange
  queue:
    create: user-queue-create
    update: user-queue-update
    delete: user-queue-delete
    restore: user-queue-restore
    addRole: user-queue-add-role
    removeRole: user-queue-remove-role
  routingKey:
    create: user.create
    update: user.update
    delete: user.delete
    restore: user.restore
    addRole: user.add.role
    removeRole: user.remove.role

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
