spring:
  application:
    name: auth-service
  rabbitmq:
    host: localhost

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret-key: "6bc18dff62463c49343d083ae0e523fbfb88d4d45b4a9cb62e86d0c53bd9b870"
  authorities-key: "roles"
  access-token-expiration: 3600000 # an hour
  refresh-token-expiration: 86400000 # a day

redis:
  host: "localhost"
  port: "6379"

rabbitmq:
  exchange: user-exchange
  queue:
    create: user-queue-create
    update: user-queue-update
    delete: user-queue-delete
    restore: user-queue-restore
    addRole: user-queue-add-role
    removeRole: user-queue-remove-role
  routingKey:
    create: user.create
    update: user.update
    delete: user.delete
    restore: user.restore
    addRole: user.add.role
    removeRole: user.remove.role