spring:
  application:
    name: rate-hub-consumer-opensearch
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ratehub-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true

server:
  port: 8086

topics:
  raw: ratehub.raw
  calculated: ratehub.calculated

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

opensearch:
  host: localhost
  port: 9200
  scheme: http
  index-name: rates

logging:
  level:
    root: INFO
    org.opensearch.client: WARN
