spring:
  application:
    name: rest-data-provider-service
  data:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

simulator:
  update-interval-millis: 5000
  max-updates: 0  # 0 => sınırsız
  # 2 parite örneği için 2x2 korelasyon matrisi
  correlationMatrix:
    - [1.0, 0.35]
    - [0.35, 1.0]

  rates:
    - rateName: "EURUSD"
      initialPrice: 1.05
      drift: 0.0
      baseSpread: 0.001
      garchParams:
        omega: 0.000001
        alpha: 0.10
        beta: 0.85
      jumpIntensity: 0.0005   # lambda
      jumpMean: 0.0
      jumpVol:  0.02
      useMeanReversion: false
      kappa: 0.0
      theta: 1.10

    - rateName: "USDTRY"
      initialPrice: 18.0
      drift: 0.0002
      baseSpread: 0.05
      garchParams:
        omega: 0.00001
        alpha: 0.12
        beta: 0.80
      jumpIntensity: 0.0008
      jumpMean: 0.0
      jumpVol: 0.05
      useMeanReversion: false
      kappa: 0.0
      theta: 18.5