spring:
  application:
    name: rest-data-provider
  data:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

simulator:
  update-interval-millis: 5000       # Her 5 saniyede bir update
  max-updates: 0                    # 0 = sınırsız

  # Korelasyon matrisi (boyut=3x3 örneği)
  correlationMatrix:
    - [1.0, 0.20, 0.10]
    - [0.20, 1.0, 0.30]
    - [0.10, 0.30, 1.0]

  # modelType: "GARCH11", "EGARCH" veya "GJR-EGARCH"
  modelType: "GJR-EGARCH"

  # Basit veya Markov tabanlı rejim geçişi
  enableRegimeSwitching: true
  useMarkovSwitching: true

  # NxN Markov matrisi örneği (burada 3 rejimlik bir örnek)
  # 0: LOW_VOL, 1: MID_VOL, 2: HIGH_VOL (örnek)
  regimeTransitionMatrix:
    - [0.80, 0.15, 0.05]
    - [0.10, 0.75, 0.15]
    - [0.05, 0.15, 0.80]

  regimeLowVol:
    volScale: 1.0
    meanDuration: 200
    transitionProb: 0.05
  regimeHighVol:
    volScale: 3.0
    meanDuration: 50
    transitionProb: 0.10

  # Haber/Olay şokları
  eventShocks:
    - name: "FOMC Rate Hike"
      dateTime: "2025-01-15T12:00:00Z"
      jumpMean: 0.005
      jumpVol: 0.010
    - name: "Geopolitical Tension"
      dateTime: "2025-02-20T09:00:00Z"
      jumpMean: 0.01
      jumpVol: 0.015

  # Makroekonomik göstergeler
  # Makro veri kaynağı (örnek)
  macroDataApiUrl: "https://macro-api.free.beeceptor.com/api/macro-data"
  macroIndicators:
    - name: "InterestRate"
      value: 0.05
      sensitivityToDrift: 1.0
      sensitivityToVol: 1.0
    - name: "Inflation"
      value: 0.03
      sensitivityToDrift: 0.5
      sensitivityToVol: 2.0

  # Hafta sonu gap
  weekendHandling:
    enabled: true
    weekendGapJumpMean: 0.001
    weekendGapJumpVol: 0.005

  # Seans bazlı vol multiplier
  sessionVolFactors:
    - startHour: 0
      endHour: 6
      volMultiplier: 0.5
    - startHour: 6
      endHour: 13
      volMultiplier: 1.0
    - startHour: 13
      endHour: 17
      volMultiplier: 1.5
    - startHour: 17
      endHour: 24
      volMultiplier: 1.0

  # Hacim bazlı volatilite ölçeklendirme
  volumeVolatilityScalingEnabled: true
  volumeVolatilityFactor: 0.0001

  # Tatil listesi
  holidays:
    - startDateTime: "2024-12-24T00:00:00Z"
      endDateTime:   "2024-12-26T00:00:00Z"
      name: "Christmas"
    - startDateTime: "2025-01-01T00:00:00Z"
      endDateTime:   "2025-01-02T00:00:00Z"
      name: "New Year"

  # Tarihsel veri path (CSV, JSON vb.)
  historicalDataPath: "src/main/resources/data/historical_fx.csv"

  # Kur tanımları (Örnek)
  rates:
    - rateName: "EURUSD"
      initialPrice: 1.037
      drift: 0.0002
      baseSpread: 0.0002
      garchParams:
        omega:  0.0000001
        alpha: 0.05
        beta: 0.90
      jumpIntensity: 0.001
      jumpMean: 0.0
      jumpVol:  0.0005
      useMeanReversion: true
      kappa: 1.0
      theta: 1.037

    - rateName: "USDTRY"
      initialPrice: 18.0
      drift: 0.0005
      baseSpread: 0.02
      garchParams:
        omega:  0.000001
        alpha: 0.10
        beta: 0.85
      jumpIntensity: 0.001
      jumpMean: 0.002
      jumpVol: 0.02
      useMeanReversion: true
      kappa: 0.05
      theta: 18.5

    - rateName: "XAUUSD"
      initialPrice: 1850.0
      drift: 0.0001
      baseSpread: 0.5
      garchParams:
        omega:  0.000002
        alpha: 0.05
        beta: 0.90
      jumpIntensity: 0.0003
      jumpMean: 0.0
      jumpVol: 0.5
      useMeanReversion: false
      kappa: 0.0
      theta: 1800.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
