spring:
  application:
    name: rest-data-provider
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

simulator:
  update-interval-millis: 1000
  max-updates: 0
  modelType: "EGARCH"
  
  correlationMatrix:
    - [1.0, 0.20, 0.10]
    - [0.20, 1.0, 0.30]
    - [0.10, 0.30, 1.0]

  shockConfig:
    smallShockWeekly: 2.5
    mediumShockMonthly: 1.5
    bigShockYearly: 1.0
    smallShockMinPct: 0.0001
    smallShockMaxPct: 0.0005
    mediumShockMinPct: 0.001
    mediumShockMaxPct: 0.005
    bigShockMinPct: 0.01
    bigShockMaxPct: 0.02

  eventShocks:
    - name: "FedRateDecision"
      dateTime: 2025-03-12T02:08:00Z
      jumpMean: 0.01
      jumpVol: 0.01

    - name: "ECBAnnouncement"
      dateTime: 2025-04-15T09:00:00Z
      jumpMean: -0.01
      jumpVol: 0.02

  macroIndicators: []
  #  - name: "Inflation"
  #    value: 5.0
  #    sensitivityToDrift: 0.01
  #    sensitivityToVol: 0.02

  #  - name: "GDPGrowth"
  #    value: 3.2
  #    sensitivityToDrift: -0.005
  #    sensitivityToVol: 0.01

  weekendGapVolatility: 0.002
  weekendShockFactor: 1.0

  sessionVolFactors:
    - startHour: 0
      endHour: 6
      volMultiplier: 0.9
    - startHour: 6
      endHour: 13
      volMultiplier: 1.1
    - startHour: 13
      endHour: 17
      volMultiplier: 1.3
    - startHour: 17
      endHour: 24
      volMultiplier: 1.0

  holidays:
    - startDateTime: "2024-12-24T00:00:00Z"
      endDateTime:   "2024-12-26T00:00:00Z"
      name: "Christmas"
    - startDateTime: "2025-01-01T00:00:00Z"
      endDateTime:   "2025-01-02T00:00:00Z"
      name: "New Year"

  rates:
    - rateName: "EURUSD"
      initialPrice: 1.0481
      drift: 0.02
      baseSpread: 0.0001
      garchParams:
        omega: 0.9
        alpha: 0.1
        beta: 0.99999
      useMeanReversion: true
      kappa: 0.001
      theta: 1.0481

    - rateName: "USDTRY"
      initialPrice: 18.50
      drift: 0.05
      baseSpread: 0.02
      garchParams:
        omega: 1e-12
        alpha: 0.0001
        beta: 0.999
      useMeanReversion: true
      kappa: 0.01
      theta: 18.50

    - rateName: "XAUUSD"
      initialPrice: 1850.0
      drift: 0.0
      baseSpread: 0.3
      garchParams:
        omega: 1e-12
        alpha: 0.0001
        beta: 0.999
      useMeanReversion: true
      kappa: 0.0
      theta: 0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
