spring:
  application:
    name: rest-data-provider
  data:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

simulator:
  update-interval-millis: 5000
  max-updates: 0
  correlationMatrix:
    - [1.0, 0.20, 0.10]
    - [0.20, 1.0, 0.30]
    - [0.10, 0.30, 1.0]

  rates:
    - rateName: "EURUSD"
      initialPrice: 1.037
      drift: 0.0
      baseSpread: 0.0002
      garchParams:
        omega:  0.00000002
        alpha: 0.02
        beta: 0.95
      jumpIntensity: 0.0002
      jumpMean: 0.0
      jumpVol:  0.0005
      useMeanReversion: true
      kappa: 2.0
      theta: 1.037

    - rateName: "USDTRY"
      initialPrice: 18.0
      drift: 0.0005
      baseSpread: 0.02
      garchParams:
        omega:  0.000001
        alpha: 0.10
        beta: 0.85
      jumpIntensity: 0.0005
      jumpMean: 0.002
      jumpVol: 0.02
      useMeanReversion: true
      kappa: 0.05
      theta: 18.5

    - rateName: "XAUUSD"
      initialPrice: 1850.0
      drift: 0.0001
      baseSpread: 0.5
      garchParams:
        omega:  0.000002
        alpha: 0.05
        beta: 0.90
      jumpIntensity: 0.0003
      jumpMean: 0.0
      jumpVol: 0.5
      useMeanReversion: false
      kappa: 0.0
      theta: 1800.0

  # Piyasa oturum çarpanları (örnek)
  sessionVolFactors:
    - startHour: 0
      endHour: 6
      volMultiplier: 0.5    # Gece: düşük vol
    - startHour: 6
      endHour: 13
      volMultiplier: 1.0    # Asya sonu + Londra açılışı
    - startHour: 13
      endHour: 17
      volMultiplier: 1.5    # Londra-NY çakışması
    - startHour: 17
      endHour: 24
      volMultiplier: 1.0    # NY akşam

  # Hafta sonu mantığı
  weekendHandling:
    enabled: true
    weekendGapJumpMean: 0.001
    weekendGapJumpVol: 0.005

  # Regime switching
  enableRegimeSwitching: true
  regimeLowVol:
    volScale: 1.0
    meanDuration: 200      # ortalama 200 adım düşük vol
    transitionProb: 0.05   # bir adımda high vol'a geçiş ihtimali
  regimeHighVol:
    volScale: 3.0
    meanDuration: 50
    transitionProb: 0.10
