spring:
  application:
    name: user-management-service
  rabbitmq:
    host: localhost

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

rabbitmq:
  exchange: user-exchange
  queue:
    create: user-queue-create
    update: user-queue-update
    delete: user-queue-delete
    restore: user-queue-restore
    addRole: user-queue-add-role
    removeRole: user-queue-remove-role
  routingKey:
    create: user.create
    update: user.update
    delete: user.delete
    restore: user.restore
    addRole: user.add.role
    removeRole: user.remove.role